Improve mail syncing
This uses BitBar v2 beta 10 and up, making use of the stdout streaming
for the main mail sync job. Which now also is controlled by BitBar,
doing away with launchctl.

diff --git a/mail/sync-mail b/mail/sync-mail
--- a/mail/sync-mail
+++ b/mail/sync-mail
@@ -1,4 +1,12 @@
 #!/bin/zsh -e
 
-offlineimap
+function fail {
+    echo ":warning: failed"
+    echo "~~~"
+    exit 0
+}
+
+echo "syncing..."
+echo "~~~"
+offlineimap >> /tmp/sync-mail.log 2>&1 || fail
 ~/bin/notmuch-poll
